// One place for every hover explanation in the product. Keys are stable ids
// used by <InfoTip k="..." />. Keep entries to one or two plain sentences.

export const HELP: Record<string, string> = {
  // Taxonomy
  vertical: 'A business line with its own channels, tasks and budget. Lyzr is the primary vertical: its board shows every vertical’s tasks, and you can add tasks for any vertical from it. GSI and others show only their own.',
  category: 'A group is only a folder for channels (Paid, Organic, Events). Nothing is owned or assigned at this level; it organises the channel list and can carry a budget.',
  channel: 'A marketing motion with owners, targets, budget and tasks (Paid Ads, Email, Content). Channels can have sub-channels.',
  sub_channel: 'A channel nested under a parent (LinkedIn Ads under Paid Ads). It has everything a channel has and inherits the parent function.',
  function: 'A domain is the same discipline across verticals (Content, Social, Paid). Linking a channel to a domain lets the domain owner see that work in every vertical at once.',
  tier: 'Priority of the channel in the plan: Gold = must win, Silver = important, Bronze = nice to have, Hygiene = keep the lights on.',
  category_icon: 'Optional pictogram for the category. Cosmetic only.',
  task: 'A piece of work on a channel: an activity with owners, a due date, priority and status. Can hold sub-activities and a checklist.',
  sub_activity: 'A child task under an activity. Has its own owners, status and due date.',
  checklist: 'Small steps inside a task. Tick them off; they do not have owners or dates.',
  also_shows_in: 'Multi-homing: the task keeps one home channel but also appears on other channels, even in another vertical.',

  // People and permissions
  admin: 'Global administrator. Creates verticals and functions, manages users, edits everything everywhere.',
  vertical_owner: 'Manages one vertical: its channels, owners, budgets, task fields and resources. Set by an admin.',
  function_owner: 'Domain owner: default owner for every channel of that domain across verticals, unless a vertical sets its own channel owners.',
  channel_owner: 'Owns a channel and its tasks. A task without an owner inherits the channel owners.',
  member: 'Everyone who signs in. Members see everything and can create and update tasks, comments and checklists.',
  task_owner: 'Owner = the person doing the task (what Jira calls the assignee). The first owner is the main one, answerable for finishing it; the rest help. Whoever wrote the task up is recorded separately as "Created by" and is not an owner unless they are also doing it.',
  pending_owner: 'This person has not signed in yet. Their ownership and assignments attach automatically the first time they sign in with Microsoft.',

  // Views
  workspace_home: 'The company view, for admins and leadership: every vertical and domain at a glance, the campaign banner, your day and recent activity.',
  space_dashboard: 'A vertical’s own home: tasks, what goes live this week, budget and activity. Inside Lyzr it covers every vertical.',
  calendar: 'Tasks by due date. Use the arrows or pick any range; filter by owner, channel and status.',
  tracker: 'Results view: tasks that went live or finished, with their results (result achieved, money spent, proof link).',
  weekly: 'Planned versus delivered: everything due in the period, split into done, not done and overdue carried in from earlier.',
  owners: 'Each person with open, overdue and live counts. Click through for their tasks, mentions, calendar and activity.',
  budgets: 'Budget periods at vertical, group or channel level, and how much tasks have planned against each.',
  leads_pipeline: 'Read-only HubSpot lead pull, email-interaction CSVs and lead imports, with per-lead outreach tracking. Enabled per vertical.',
  history: 'Every logged change, who made it and when.',
  functions_view: 'One domain across all verticals: its channels, tasks and weekly results everywhere it runs.',
  resources: 'Curated links for this vertical: sheets, asset folders, live pages.',
  saved_views: 'Save the current filters and sort under a name so you can reload them later.',
  feature_flags: 'Which optional modules this vertical shows. GSI integrations (HubSpot pull, Instantly report) are wired for GSI today.',
  template: 'A snapshot of a vertical’s groups, channels, sub-channels and task fields (no tasks or owners). New verticals can start from one.',
  date_range: 'Pick a preset, or two dates on the calendar. The arrows step forward and back by the same length.',
  date_field: 'Which date the range applies to: when the task is due, was completed, was created, or went live.',
  status: 'Colour tells you where it stands: grey Not started, yellow In progress, green Live or Done, red Blocked. Cancelled is hidden by default.',
  priority: 'Critical (P0), High (P1), Medium (P2), Low (P3), Backlog (P4). The importance tier maps Gold = Critical, Silver = High, Bronze = Medium.',
  tracker_fields: 'The Results section: what was achieved, what it cost and a proof link, filled in once a task is live or done. Locks 45 days after completion; admins can override.',
  custom_fields: 'Extra planning or tracker fields per channel (text, number, currency, date, dropdown...). Cascade to sub-channels.',
  campaign: 'A hero item the whole team rallies around: a product launch, a thunderclap or a big campaign. It sits as a banner on every dashboard, links tasks from any channel, and has its own tracker page.',
  launch: 'A product or feature launch. Link every launch task to it so leadership sees one progress bar.',
  thunderclap: 'Everyone must do one specific action (repost, comment, share) by a date. Each participant ticks their own row; the banner shows who is done.',
  champion: 'Campaign leads: the people driving it. They can edit it and are shown on the banner.',
  my_board: 'Your own home: the campaign banner, your channels across every vertical, and what you owe this week.',
  assistant: 'Ask it two things: create a task (it fills the form, you press Create) or find a task (status, owners and a link). It does nothing else.',
  leadership: 'A read-across badge. Leadership sees the whole company (every vertical, domain, campaign and task) and edits nothing unless they press Edit on a task.',
  vertical_member: 'Anyone who works in the vertical. Members create tasks and sub-tasks there. Owners of anything in the vertical are members automatically.',
  suggest_edit: 'Not an owner of this task? Propose the change here. The owners see it and accept or reject it in one click.',
  task_history: 'Every change to this task, written by the database: who, what, from, to, when.',
  people_map: 'Who is where: each row is a domain or channel, each column a vertical, each cell the people who own it. Dimmed names are inherited from the domain.',
  cross_channel: 'A sub-task can live on a different channel from its parent (design for a webinar sits on the Design board). It shows on both, counts once.',
  group: 'Only a folder for channels. Nothing is owned or assigned at this level; it can carry a budget that its channels roll into.',
  notifications: 'You hear about everything on tasks you are related to: asked to own, comments, edits, checklist ticks, new sub-tasks, suggestions, and thunderclap asks. Related = owner, creator, parent-task owner, channel owner above it.',
  linked_accounts: 'You are one person with one account. Add Google, Microsoft or Slack sign-in here; your lyzr.ai and lyzr.com addresses both attach to it. Never create a second account.',
  overview: 'The whole plan as one collapsible tree: vertical, group, channel, sub-channel, task, sub-task. Each row shows open, done and overdue for everything underneath it.',
  recurring: 'Repeat a task automatically: every N days, weeks or months, on chosen weekdays, ending never, on a date or after N times.',
}

export type HelpKey = keyof typeof HELP
