-- ============================================================
-- RESET_ALL.sql  (GENERATED by scripts/build-reset-sql.mjs — do not hand-edit)
-- Full clean reset of the GSI Tracker database + replay of migrations
-- 001,002,003,004,005,007,008,009,010 (006 = old-taxonomy field seed, skipped).
--
-- Paste this ENTIRE file into Supabase Dashboard > SQL Editor > Run.
-- DESTRUCTIVE: drops every table in the public schema. Auth accounts
-- (auth.users) are preserved and re-mirrored at the end.
-- After this: run  node scripts/seed-gtm.mjs  to load the GTM blueprint.
-- ============================================================

-- ---------- TEARDOWN ----------
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP POLICY IF EXISTS "auth_upload"     ON storage.objects;
DROP POLICY IF EXISTS "auth_read_files" ON storage.objects;
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
COMMENT ON SCHEMA public IS 'standard public schema';
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL   ON SCHEMA public TO postgres, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES    TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON ROUTINES  TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;

-- ############################################################
-- 001_initial_schema.sql
-- ############################################################
-- ============================================================
-- Lyzr GSI/SI Marketing Tracker - Core v0 Schema
-- Run this in Supabase SQL Editor (Dashboard > SQL Editor > New Query)
-- ============================================================

-- ============ ENUMS ============

CREATE TYPE user_role AS ENUM ('admin', 'member');
CREATE TYPE field_type AS ENUM (
  'text', 'long_text', 'number', 'currency',
  'date', 'date_range',
  'dropdown', 'multi_select', 'checkbox',
  'url', 'email', 'phone',
  'person', 'file'
);
CREATE TYPE field_surface AS ENUM ('planning', 'tracker');
CREATE TYPE task_status AS ENUM ('not_started', 'in_progress', 'live', 'blocked', 'done', 'cancelled');
CREATE TYPE task_priority AS ENUM ('P0', 'P1', 'P2', 'P3');
CREATE TYPE assignment_role AS ENUM ('primary', 'secondary', 'tertiary', 'other');
CREATE TYPE mention_surface AS ENUM (
  'task_description', 'task_comment', 'checklist_item', 'blocked_description', 'insight'
);
CREATE TYPE budget_period_type AS ENUM (
  'one_time', 'monthly', 'quarterly', 'half_yearly', 'annual', 'custom'
);
CREATE TYPE budget_scope_type AS ENUM ('global', 'category', 'channel');
CREATE TYPE notification_type AS ENUM (
  'assigned', 'mentioned', 'comment',
  'status_change', 'dependency_completed',
  'subtask_completed', 'parent_blocked',
  'budget_overrun_warning', 'overdue'
);

-- ============ USERS ============

CREATE TABLE users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT UNIQUE NOT NULL,
  display_name TEXT,
  avatar_url TEXT,
  role user_role NOT NULL DEFAULT 'member',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============ TAXONOMY ============

CREATE TABLE categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  icon TEXT,
  sort_order INT NOT NULL DEFAULT 0,
  is_active BOOL NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE channels (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id UUID NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
  parent_channel_id UUID REFERENCES channels(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  slug TEXT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active BOOL NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (category_id, parent_channel_id, slug)
);

CREATE INDEX channels_category_idx ON channels(category_id);
CREATE INDEX channels_parent_idx ON channels(parent_channel_id);

-- ============ CHANNEL FIELDS (for seed data) ============

CREATE TABLE channel_fields (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  slug TEXT NOT NULL,
  field_type field_type NOT NULL,
  surface field_surface NOT NULL,
  is_required BOOL NOT NULL DEFAULT FALSE,
  options JSONB,
  formula TEXT,
  is_auto_calc BOOL NOT NULL DEFAULT FALSE,
  description TEXT,
  sort_order INT NOT NULL DEFAULT 0,
  cascades_to_children BOOL NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (channel_id, slug)
);

CREATE INDEX channel_fields_channel_idx ON channel_fields(channel_id);
CREATE INDEX channel_fields_surface_idx ON channel_fields(surface);

-- ============ BUDGET PERIODS ============

CREATE TABLE budget_periods (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  scope_type budget_scope_type NOT NULL,
  scope_id UUID,
  period_type budget_period_type NOT NULL,
  period_label TEXT NOT NULL,
  starts_on DATE NOT NULL,
  ends_on DATE NOT NULL,
  total_budget NUMERIC(12,2) NOT NULL,
  created_by UUID NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  notes TEXT,
  CHECK (ends_on >= starts_on)
);

CREATE INDEX budget_periods_scope_idx ON budget_periods(scope_type, scope_id);
CREATE INDEX budget_periods_dates_idx ON budget_periods(starts_on, ends_on);

-- ============ TASKS ============

CREATE TABLE tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE RESTRICT,
  parent_task_id UUID REFERENCES tasks(id) ON DELETE CASCADE,
  nesting_level INT NOT NULL DEFAULT 0,
  title TEXT NOT NULL,
  description TEXT,
  priority task_priority NOT NULL DEFAULT 'P2',
  status task_status NOT NULL DEFAULT 'not_started',
  due_date DATE,
  result_url TEXT,
  result_file_path TEXT,
  budget_allocated NUMERIC(12,2),
  budget_period_id UUID REFERENCES budget_periods(id),
  blocked_by_user_id UUID REFERENCES users(id),
  blocked_by_email TEXT,
  blocked_reason TEXT,
  planning_fields JSONB NOT NULL DEFAULT '{}'::jsonb,
  tracker_fields JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  went_live_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  CHECK (nesting_level >= 0 AND nesting_level <= 2)
);

CREATE INDEX tasks_channel_idx ON tasks(channel_id);
CREATE INDEX tasks_parent_idx ON tasks(parent_task_id);
CREATE INDEX tasks_status_idx ON tasks(status);
CREATE INDEX tasks_due_date_idx ON tasks(due_date);
CREATE INDEX tasks_created_by_idx ON tasks(created_by);
CREATE INDEX tasks_budget_period_idx ON tasks(budget_period_id);

-- ============ TASK ASSIGNMENTS ============

CREATE TABLE task_assignments (
  task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role assignment_role NOT NULL DEFAULT 'other',
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  assigned_by UUID REFERENCES users(id),
  PRIMARY KEY (task_id, user_id)
);

CREATE INDEX task_assignments_user_idx ON task_assignments(user_id);

CREATE UNIQUE INDEX task_assignments_primary_unique
  ON task_assignments(task_id) WHERE role = 'primary';

-- ============ CHECKLIST ITEMS ============

CREATE TABLE checklist_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  is_done BOOL NOT NULL DEFAULT FALSE,
  done_at TIMESTAMPTZ,
  done_by UUID REFERENCES users(id),
  sort_order INT NOT NULL DEFAULT 0,
  created_by UUID NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX checklist_task_idx ON checklist_items(task_id);

-- ============ COMMENTS ============

CREATE TABLE task_comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  body TEXT NOT NULL,
  file_path TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX task_comments_task_idx ON task_comments(task_id);

-- ============ MENTIONS ============

CREATE TABLE mentions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  surface mention_surface NOT NULL,
  surface_ref_id UUID,
  mentioned_user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  mentioned_email TEXT,
  mentioned_by UUID NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE pending_mentions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL,
  task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  surface mention_surface NOT NULL,
  surface_ref_id UUID,
  resolved_user_id UUID REFERENCES users(id),
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX mentions_user_idx ON mentions(mentioned_user_id);
CREATE INDEX mentions_task_idx ON mentions(task_id);

-- ============ ACTIVITY LOG ============

CREATE TABLE activity_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id UUID REFERENCES tasks(id) ON DELETE CASCADE,
  actor_id UUID REFERENCES users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  from_value JSONB,
  to_value JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX activity_log_task_idx ON activity_log(task_id);
CREATE INDEX activity_log_created_idx ON activity_log(created_at DESC);

-- ============ NOTIFICATIONS ============

CREATE TABLE notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  task_id UUID REFERENCES tasks(id) ON DELETE CASCADE,
  type notification_type NOT NULL,
  payload JSONB NOT NULL,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX notifications_user_unread_idx ON notifications(user_id) WHERE read_at IS NULL;

-- ============ BUDGET SUMMARY VIEW ============

CREATE VIEW budget_period_summary AS
SELECT
  bp.id AS budget_period_id,
  bp.period_label,
  bp.scope_type,
  bp.scope_id,
  bp.total_budget,
  COALESCE(SUM(t.budget_allocated), 0) AS allocated,
  bp.total_budget - COALESCE(SUM(t.budget_allocated), 0) AS remaining,
  COUNT(t.id) FILTER (WHERE t.budget_allocated IS NOT NULL) AS task_count
FROM budget_periods bp
LEFT JOIN tasks t ON t.budget_period_id = bp.id
GROUP BY bp.id;

-- ============ TRIGGERS ============

-- Auto-update updated_at on tasks
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER tasks_updated_at
  BEFORE UPDATE ON tasks FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Auto-set timestamps on status transitions
CREATE OR REPLACE FUNCTION handle_task_status_change()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.status = 'live' AND OLD.status != 'live' THEN
    NEW.went_live_at = COALESCE(NEW.went_live_at, now());
  END IF;
  IF NEW.status = 'done' AND OLD.status != 'done' THEN
    NEW.completed_at = COALESCE(NEW.completed_at, now());
  END IF;
  IF NEW.status = 'cancelled' AND OLD.status != 'cancelled' THEN
    NEW.cancelled_at = COALESCE(NEW.cancelled_at, now());
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER tasks_status_change
  BEFORE UPDATE ON tasks FOR EACH ROW
  WHEN (OLD.status IS DISTINCT FROM NEW.status)
  EXECUTE FUNCTION handle_task_status_change();

-- Mirror auth.users to public.users
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.users (id, email, display_name, avatar_url, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
    NEW.raw_user_meta_data->>'avatar_url',
    CASE WHEN NEW.email = 'kailash.gm@lyzr.ai' THEN 'admin'::user_role ELSE 'member'::user_role END
  );
  -- Resolve any pending mentions for this email
  UPDATE pending_mentions SET resolved_user_id = NEW.id, resolved_at = now()
    WHERE email = NEW.email AND resolved_user_id IS NULL;
  -- Create resolved mentions from pending
  INSERT INTO mentions (task_id, surface, surface_ref_id, mentioned_user_id, mentioned_email, mentioned_by)
  SELECT pm.task_id, pm.surface, pm.surface_ref_id, NEW.id, NEW.email, NEW.id
  FROM pending_mentions pm
  WHERE pm.email = NEW.email AND pm.resolved_user_id = NEW.id;
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- ============ RLS (PERMISSIVE - will tighten later) ============

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE channel_fields ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE checklist_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE mentions ENABLE ROW LEVEL SECURITY;
ALTER TABLE pending_mentions ENABLE ROW LEVEL SECURITY;
ALTER TABLE budget_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Permissive read for all authenticated users on all tables
CREATE POLICY "auth_read" ON users FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_read" ON categories FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_read" ON channels FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_read" ON channel_fields FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_read" ON tasks FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_read" ON task_assignments FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_read" ON checklist_items FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_read" ON task_comments FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_read" ON mentions FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_read" ON pending_mentions FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_read" ON budget_periods FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_read" ON activity_log FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_read" ON notifications FOR SELECT TO authenticated USING (true);

-- Permissive write for all authenticated users (will tighten later)
CREATE POLICY "auth_insert" ON tasks FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_update" ON tasks FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_delete" ON tasks FOR DELETE TO authenticated USING (true);

CREATE POLICY "auth_insert" ON task_assignments FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_update" ON task_assignments FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_delete" ON task_assignments FOR DELETE TO authenticated USING (true);

CREATE POLICY "auth_insert" ON checklist_items FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_update" ON checklist_items FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_delete" ON checklist_items FOR DELETE TO authenticated USING (true);

CREATE POLICY "auth_insert" ON task_comments FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_update" ON task_comments FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_delete" ON task_comments FOR DELETE TO authenticated USING (true);

CREATE POLICY "auth_insert" ON mentions FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_insert" ON pending_mentions FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "auth_insert" ON budget_periods FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_update" ON budget_periods FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_delete" ON budget_periods FOR DELETE TO authenticated USING (true);

CREATE POLICY "auth_insert" ON activity_log FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "auth_insert" ON notifications FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_update" ON notifications FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- ============ STORAGE BUCKET ============

INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES ('task-results', 'task-results', false, 2097152)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "auth_upload" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'task-results');
CREATE POLICY "auth_read_files" ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'task-results');


-- (old taxonomy seed stripped — GTM blueprint is seeded by scripts/seed-gtm.mjs)

-- ############################################################
-- 002_phase2_schema.sql
-- ############################################################
-- ==========================================
-- PHASE 2 SCHEMA MIGRATION
-- ==========================================

-- 1. Create Recurrence Pattern type and templates table
CREATE TYPE recurrence_pattern AS ENUM ('daily', 'weekly', 'biweekly', 'monthly', 'custom');

CREATE TABLE recurring_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE RESTRICT,
  title TEXT NOT NULL,
  description TEXT,
  default_priority task_priority NOT NULL DEFAULT 'P2',
  default_planning_fields JSONB NOT NULL DEFAULT '{}'::jsonb,
  pattern recurrence_pattern NOT NULL,
  custom_interval_days INT,
  starts_on DATE NOT NULL,
  ends_on DATE,
  next_due_date DATE NOT NULL,
  default_assignees UUID[] NOT NULL DEFAULT '{}',
  created_by UUID NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  is_active BOOL NOT NULL DEFAULT true
);

CREATE INDEX recurring_templates_next_due_idx ON recurring_templates(next_due_date) WHERE is_active = true;

-- 2. Alter tasks table to reference templates and add freeze date
ALTER TABLE tasks ADD COLUMN recurring_template_id UUID REFERENCES recurring_templates(id) ON DELETE SET NULL;
ALTER TABLE tasks ADD COLUMN tracker_frozen_at TIMESTAMPTZ;

-- 3. Create task dependencies table
CREATE TABLE task_dependencies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  depends_on_task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (task_id, depends_on_task_id),
  CHECK (task_id <> depends_on_task_id)
);

CREATE INDEX task_deps_task_idx ON task_dependencies(task_id);
CREATE INDEX task_deps_depends_on_idx ON task_dependencies(depends_on_task_id);

-- 4. Create weekly snapshots table
CREATE TABLE weekly_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  week_starting DATE NOT NULL UNIQUE,
  total_tasks INT NOT NULL,
  completed_tasks INT NOT NULL,
  blocked_tasks INT NOT NULL,
  live_tasks INT NOT NULL,
  in_progress_tasks INT NOT NULL,
  not_started_tasks INT NOT NULL,
  cancelled_tasks INT NOT NULL,
  by_category JSONB NOT NULL,
  by_owner JSONB NOT NULL,
  budget_summary JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 5. Create slack settings table
CREATE TABLE slack_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id UUID REFERENCES categories(id) ON DELETE CASCADE,
  slack_channel_id TEXT NOT NULL,
  notify_on_create BOOL NOT NULL DEFAULT true,
  notify_on_complete BOOL NOT NULL DEFAULT true,
  notify_on_blocked BOOL NOT NULL DEFAULT true,
  notify_on_live BOOL NOT NULL DEFAULT true,
  notify_on_overdue BOOL NOT NULL DEFAULT true,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============ Enable Row Level Security (RLS) ============

ALTER TABLE recurring_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_dependencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE slack_settings ENABLE ROW LEVEL SECURITY;

-- ============ RLS Policies ============

CREATE POLICY "auth_read" ON recurring_templates FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_write" ON recurring_templates FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "auth_read" ON task_dependencies FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_write" ON task_dependencies FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "auth_read" ON weekly_snapshots FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_write" ON weekly_snapshots FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "auth_read" ON slack_settings FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_write" ON slack_settings FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 6. Trigger update to set tracker_frozen_at on status changes
CREATE OR REPLACE FUNCTION handle_task_status_change()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.status = 'live' AND OLD.status != 'live' THEN
    NEW.went_live_at = COALESCE(NEW.went_live_at, now());
    NEW.tracker_frozen_at = COALESCE(NEW.tracker_frozen_at, now() + INTERVAL '45 days');
  END IF;
  IF NEW.status = 'done' AND OLD.status != 'done' THEN
    NEW.completed_at = COALESCE(NEW.completed_at, now());
    NEW.tracker_frozen_at = COALESCE(NEW.tracker_frozen_at, now() + INTERVAL '45 days');
  END IF;
  IF NEW.status = 'cancelled' AND OLD.status != 'cancelled' THEN
    NEW.cancelled_at = COALESCE(NEW.cancelled_at, now());
  END IF;
  RETURN NEW;
END;
$$;


-- ############################################################
-- 003_pending_slack_notifications.sql
-- ############################################################
-- ==========================================
-- CREATE PENDING SLACK NOTIFICATIONS TABLE
-- ==========================================

CREATE TABLE pending_slack_notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending', -- 'pending', 'sent', 'failed'
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_at TIMESTAMPTZ
);

-- Enable RLS
ALTER TABLE pending_slack_notifications ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read/write
CREATE POLICY "auth_read" ON pending_slack_notifications FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_write" ON pending_slack_notifications FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ############################################################
-- 004_hubspot_tables.sql
-- ############################################################
-- ==========================================
-- CREATE HUBSPOT SYNC TABLES
-- ==========================================

CREATE TABLE hubspot_connection (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  portal_id TEXT NOT NULL UNIQUE,
  access_token_encrypted TEXT NOT NULL,
  refresh_token_encrypted TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  connected_by UUID NOT NULL REFERENCES users(id),
  connected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_sync_at TIMESTAMPTZ
);

CREATE TABLE hubspot_synced_contacts (
  hubspot_contact_id TEXT PRIMARY KEY,
  email TEXT NOT NULL,
  first_name TEXT,
  last_name TEXT,
  company TEXT,
  lifecycle_stage TEXT,
  sequence_memberships JSONB NOT NULL DEFAULT '[]'::jsonb, -- which sequences they're enrolled in
  raw_properties JSONB NOT NULL DEFAULT '{}'::jsonb,
  synced_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable Row Level Security (RLS)
ALTER TABLE hubspot_connection ENABLE ROW LEVEL SECURITY;
ALTER TABLE hubspot_synced_contacts ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read/write connection status (admins can perform full edits)
CREATE POLICY "auth_read" ON hubspot_connection FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_write" ON hubspot_connection FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Allow authenticated users to read synced contacts, and writes for authenticated users (handled via service client or API)
CREATE POLICY "auth_read" ON hubspot_synced_contacts FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_write" ON hubspot_synced_contacts FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ############################################################
-- 005_apply_phase2_and_3_idempotent.sql
-- ############################################################
-- ============================================================
-- MIGRATION 005: Apply Phase 2 (originally 002) + Phase 3 (originally 003)
--   idempotently. Safe to re-run.
--
-- Why this file exists:
--   Migrations 002 and 003 were never run against the deployed DB. The code
--   in lib/actions/index.ts and lib/hooks/use-data.ts references tables and
--   columns from those migrations (recurring_templates, task_dependencies,
--   slack_settings, weekly_snapshots, pending_slack_notifications, and the
--   tasks.recurring_template_id + tasks.tracker_frozen_at columns), so every
--   mutation that touches them fails with PGRST204/205.
--
-- What this does:
--   1. Creates enum `recurrence_pattern` (skipping if it already exists).
--   2. Creates table `recurring_templates` and adds the two missing columns
--      to `tasks` (recurring_template_id, tracker_frozen_at).
--   3. Creates tables `task_dependencies`, `weekly_snapshots`, `slack_settings`.
--   4. Creates table `pending_slack_notifications` (from migration 003).
--   5. Replaces `handle_task_status_change` with the Phase 2 version that
--      sets `tracker_frozen_at` 45 days after live/done.
--   6. Enables RLS + (re-)creates permissive auth policies on all new tables.
--   7. Adds indexes.
--
-- Order matters:
--   - Types and tables created before columns that reference them.
--   - Trigger function replaced AFTER the column it references is added.
-- ============================================================

-- ---------- 1. Enum: recurrence_pattern ----------
DO $$ BEGIN
  CREATE TYPE recurrence_pattern AS ENUM ('daily', 'weekly', 'biweekly', 'monthly', 'custom');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ---------- 2. Table: recurring_templates ----------
CREATE TABLE IF NOT EXISTS recurring_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE RESTRICT,
  title TEXT NOT NULL,
  description TEXT,
  default_priority task_priority NOT NULL DEFAULT 'P2',
  default_planning_fields JSONB NOT NULL DEFAULT '{}'::jsonb,
  pattern recurrence_pattern NOT NULL,
  custom_interval_days INT,
  starts_on DATE NOT NULL,
  ends_on DATE,
  next_due_date DATE NOT NULL,
  default_assignees UUID[] NOT NULL DEFAULT '{}',
  created_by UUID NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  is_active BOOL NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS recurring_templates_next_due_idx
  ON recurring_templates(next_due_date) WHERE is_active = true;

-- ---------- 3. New columns on tasks ----------
ALTER TABLE tasks
  ADD COLUMN IF NOT EXISTS recurring_template_id UUID
    REFERENCES recurring_templates(id) ON DELETE SET NULL;

ALTER TABLE tasks
  ADD COLUMN IF NOT EXISTS tracker_frozen_at TIMESTAMPTZ;

-- ---------- 4. Table: task_dependencies ----------
CREATE TABLE IF NOT EXISTS task_dependencies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  depends_on_task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (task_id, depends_on_task_id),
  CHECK (task_id <> depends_on_task_id)
);

CREATE INDEX IF NOT EXISTS task_deps_task_idx ON task_dependencies(task_id);
CREATE INDEX IF NOT EXISTS task_deps_depends_on_idx ON task_dependencies(depends_on_task_id);

-- ---------- 5. Table: weekly_snapshots ----------
CREATE TABLE IF NOT EXISTS weekly_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  week_starting DATE NOT NULL UNIQUE,
  total_tasks INT NOT NULL,
  completed_tasks INT NOT NULL,
  blocked_tasks INT NOT NULL,
  live_tasks INT NOT NULL,
  in_progress_tasks INT NOT NULL,
  not_started_tasks INT NOT NULL,
  cancelled_tasks INT NOT NULL,
  by_category JSONB NOT NULL,
  by_owner JSONB NOT NULL,
  budget_summary JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- 6. Table: slack_settings ----------
CREATE TABLE IF NOT EXISTS slack_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id UUID REFERENCES categories(id) ON DELETE CASCADE,
  slack_channel_id TEXT NOT NULL,
  notify_on_create BOOL NOT NULL DEFAULT true,
  notify_on_complete BOOL NOT NULL DEFAULT true,
  notify_on_blocked BOOL NOT NULL DEFAULT true,
  notify_on_live BOOL NOT NULL DEFAULT true,
  notify_on_overdue BOOL NOT NULL DEFAULT true,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- 7. Table: pending_slack_notifications (migration 003) ----------
CREATE TABLE IF NOT EXISTS pending_slack_notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  sent_at TIMESTAMPTZ
);

-- ---------- 8. Trigger function: Phase 2 version of handle_task_status_change ----------
CREATE OR REPLACE FUNCTION handle_task_status_change()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.status = 'live' AND OLD.status != 'live' THEN
    NEW.went_live_at = COALESCE(NEW.went_live_at, now());
    NEW.tracker_frozen_at = COALESCE(NEW.tracker_frozen_at, now() + INTERVAL '45 days');
  END IF;
  IF NEW.status = 'done' AND OLD.status != 'done' THEN
    NEW.completed_at = COALESCE(NEW.completed_at, now());
    NEW.tracker_frozen_at = COALESCE(NEW.tracker_frozen_at, now() + INTERVAL '45 days');
  END IF;
  IF NEW.status = 'cancelled' AND OLD.status != 'cancelled' THEN
    NEW.cancelled_at = COALESCE(NEW.cancelled_at, now());
  END IF;
  RETURN NEW;
END;
$$;

-- Trigger itself already exists from migration 001 and is bound to the
-- function by name, so the CREATE OR REPLACE above is enough — no need
-- to DROP/CREATE the trigger.

-- ---------- 9. RLS on new tables ----------
ALTER TABLE recurring_templates        ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_dependencies          ENABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_snapshots           ENABLE ROW LEVEL SECURITY;
ALTER TABLE slack_settings             ENABLE ROW LEVEL SECURITY;
ALTER TABLE pending_slack_notifications ENABLE ROW LEVEL SECURITY;

-- ---------- 10. Policies (drop + create — no CREATE POLICY IF NOT EXISTS) ----------
DROP POLICY IF EXISTS "auth_read"  ON recurring_templates;
DROP POLICY IF EXISTS "auth_write" ON recurring_templates;
CREATE POLICY "auth_read"  ON recurring_templates FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_write" ON recurring_templates FOR ALL    TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "auth_read"  ON task_dependencies;
DROP POLICY IF EXISTS "auth_write" ON task_dependencies;
CREATE POLICY "auth_read"  ON task_dependencies FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_write" ON task_dependencies FOR ALL    TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "auth_read"  ON weekly_snapshots;
DROP POLICY IF EXISTS "auth_write" ON weekly_snapshots;
CREATE POLICY "auth_read"  ON weekly_snapshots FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_write" ON weekly_snapshots FOR ALL    TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "auth_read"  ON slack_settings;
DROP POLICY IF EXISTS "auth_write" ON slack_settings;
CREATE POLICY "auth_read"  ON slack_settings FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_write" ON slack_settings FOR ALL    TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "auth_read"  ON pending_slack_notifications;
DROP POLICY IF EXISTS "auth_write" ON pending_slack_notifications;
CREATE POLICY "auth_read"  ON pending_slack_notifications FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_write" ON pending_slack_notifications FOR ALL    TO authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- DONE. Verify with the Step 0 diagnostic again — all sections
-- should now report the Phase 2 / 3 schema is present.
-- ============================================================

-- ############################################################
-- 007_invites_and_pending_assignments.sql
-- ############################################################
-- ============================================================
-- MIGRATION 007: Invites + Pending Assignments
--
-- Why this exists:
--   The product needs:
--   (a) Admins to invite new teammates by email before they have a Supabase
--       Auth account (sends a notification email; resolves to a real user on
--       first Google SSO sign-in).
--   (b) Tasks to be assignable to an email address before that person has
--       signed in (mirroring the existing pending_mentions pattern). On first
--       sign-in, their pending assignments auto-resolve into real
--       task_assignments rows so the user lands with their work waiting.
--
-- Idempotent. Safe to re-run.
-- ============================================================

-- ---------- 1. pending_invites ----------
CREATE TABLE IF NOT EXISTS pending_invites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL UNIQUE,
  invited_by UUID REFERENCES users(id) ON DELETE SET NULL,
  email_sent_at TIMESTAMPTZ,
  email_send_error TEXT,
  resolved_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS pending_invites_unresolved_idx
  ON pending_invites(email) WHERE resolved_user_id IS NULL;

-- ---------- 2. pending_assignments ----------
CREATE TABLE IF NOT EXISTS pending_assignments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  role assignment_role NOT NULL DEFAULT 'other',
  assigned_by UUID REFERENCES users(id) ON DELETE SET NULL,
  resolved_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (task_id, email)
);

CREATE INDEX IF NOT EXISTS pending_assignments_email_idx
  ON pending_assignments(email) WHERE resolved_user_id IS NULL;

-- ---------- 3. RLS ----------
ALTER TABLE pending_invites      ENABLE ROW LEVEL SECURITY;
ALTER TABLE pending_assignments  ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "auth_read"  ON pending_invites;
DROP POLICY IF EXISTS "auth_write" ON pending_invites;
CREATE POLICY "auth_read"  ON pending_invites FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_write" ON pending_invites FOR ALL    TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "auth_read"  ON pending_assignments;
DROP POLICY IF EXISTS "auth_write" ON pending_assignments;
CREATE POLICY "auth_read"  ON pending_assignments FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_write" ON pending_assignments FOR ALL    TO authenticated USING (true) WITH CHECK (true);

-- ---------- 4. Extend handle_new_user trigger ----------
-- The existing trigger (migration 001) creates a public.users row and resolves
-- pending_mentions. We extend it to ALSO:
--   - Mark the matching pending_invite as resolved (if any)
--   - Resolve all pending_assignments for this email into real task_assignments
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  -- Mirror auth.users → public.users (unchanged from migration 001)
  INSERT INTO public.users (id, email, display_name, avatar_url, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
    NEW.raw_user_meta_data->>'avatar_url',
    CASE WHEN NEW.email = 'kailash.gm@lyzr.ai' THEN 'admin'::user_role ELSE 'member'::user_role END
  );

  -- Resolve pending mentions (unchanged from migration 001)
  UPDATE pending_mentions
     SET resolved_user_id = NEW.id, resolved_at = now()
   WHERE email = NEW.email AND resolved_user_id IS NULL;

  INSERT INTO mentions (task_id, surface, surface_ref_id, mentioned_user_id, mentioned_email, mentioned_by)
  SELECT pm.task_id, pm.surface, pm.surface_ref_id, NEW.id, NEW.email, NEW.id
    FROM pending_mentions pm
   WHERE pm.email = NEW.email AND pm.resolved_user_id = NEW.id;

  -- NEW: Mark pending invite resolved
  UPDATE pending_invites
     SET resolved_user_id = NEW.id, resolved_at = now()
   WHERE email = NEW.email AND resolved_user_id IS NULL;

  -- NEW: Materialize pending_assignments into real task_assignments.
  -- ON CONFLICT DO NOTHING avoids dup-key errors if someone got assigned
  -- both by email and (race) by user_id around the same moment.
  INSERT INTO task_assignments (task_id, user_id, role, assigned_by)
  SELECT pa.task_id, NEW.id, pa.role, pa.assigned_by
    FROM pending_assignments pa
   WHERE pa.email = NEW.email AND pa.resolved_user_id IS NULL
  ON CONFLICT (task_id, user_id) DO NOTHING;

  UPDATE pending_assignments
     SET resolved_user_id = NEW.id, resolved_at = now()
   WHERE email = NEW.email AND resolved_user_id IS NULL;

  RETURN NEW;
END;
$$;

-- Trigger binding from migration 001 references this function by name, so the
-- CREATE OR REPLACE above is enough — no need to recreate the trigger itself.

-- ============================================================
-- DONE.
-- ============================================================

-- ############################################################
-- 008_rls_hardening.sql
-- ############################################################
-- ============================================================
-- MIGRATION 008: RLS hardening per spec §6
--
-- Previously, every table had wide-open policies (USING (true)) which were
-- fine for dev but unsafe for production. This migration replaces those with
-- the per-table rules from spec §6:
--   - Admin-only writes: categories, channels, channel_fields, budget_periods,
--     slack_settings, hubspot_*
--   - Author-or-admin writes: task_comments, recurring_templates
--   - Creator-or-admin delete: tasks
--   - Self-only reads + system writes: notifications, mentions, activity_log,
--     weekly_snapshots
--   - System-only inserts (via trigger): mentions, pending_mentions, activity_log
--     (writes still go through, but only when called by SECURITY DEFINER funcs)
--
-- All reads remain open to authenticated users (you can SEE everything; admin
-- gating happens on writes).
--
-- Idempotent: safe to re-run; old policies are DROPped before recreate.
-- ============================================================

-- ---------- Helper: is_admin() ----------
-- SECURITY DEFINER so it can read public.users regardless of caller's RLS.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin'
  );
$$;

GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

-- ---------- Macro to drop ALL existing policies on a table (we recreate below) ----------
-- Postgres doesn't have "DROP ALL POLICIES" so we drop the specific names we used.
DO $$
DECLARE
  t TEXT;
  p TEXT;
  table_names TEXT[] := ARRAY[
    'users', 'categories', 'channels', 'channel_fields',
    'tasks', 'task_assignments', 'checklist_items', 'task_comments',
    'mentions', 'pending_mentions', 'task_dependencies',
    'recurring_templates', 'budget_periods', 'activity_log',
    'weekly_snapshots', 'notifications', 'slack_settings',
    'pending_slack_notifications', 'hubspot_connection',
    'hubspot_synced_contacts', 'pending_invites', 'pending_assignments'
  ];
BEGIN
  FOREACH t IN ARRAY table_names LOOP
    FOR p IN
      SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = t
    LOOP
      EXECUTE format('DROP POLICY IF EXISTS %I ON %I', p, t);
    END LOOP;
  END LOOP;
END $$;

-- ============================================================
-- USERS: read-all | update self-or-admin | delete admin
-- ============================================================
CREATE POLICY "users_read"   ON users FOR SELECT TO authenticated USING (true);
CREATE POLICY "users_update" ON users FOR UPDATE TO authenticated
  USING (auth.uid() = id OR is_admin())
  WITH CHECK (auth.uid() = id OR is_admin());
CREATE POLICY "users_delete" ON users FOR DELETE TO authenticated USING (is_admin());
-- INSERT happens via handle_new_user trigger (SECURITY DEFINER) — no policy needed.

-- ============================================================
-- CATEGORIES, CHANNELS, CHANNEL_FIELDS: read-all | write admin
-- ============================================================
CREATE POLICY "categories_read"        ON categories      FOR SELECT TO authenticated USING (true);
CREATE POLICY "categories_admin_write" ON categories      FOR ALL    TO authenticated USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY "channels_read"        ON channels      FOR SELECT TO authenticated USING (true);
CREATE POLICY "channels_admin_write" ON channels      FOR ALL    TO authenticated USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY "channel_fields_read"        ON channel_fields FOR SELECT TO authenticated USING (true);
CREATE POLICY "channel_fields_admin_write" ON channel_fields FOR ALL    TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- ============================================================
-- TASKS: read-all | insert any auth | update any auth | delete creator-or-admin
-- (Spec §6.1: tracker_fields lock past tracker_frozen_at is enforced in app code;
--  RLS could enforce it but would also block legitimate creator updates.)
-- ============================================================
CREATE POLICY "tasks_read"   ON tasks FOR SELECT TO authenticated USING (true);
CREATE POLICY "tasks_insert" ON tasks FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by);
CREATE POLICY "tasks_update" ON tasks FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "tasks_delete" ON tasks FOR DELETE TO authenticated USING (auth.uid() = created_by OR is_admin());

-- ============================================================
-- TASK_ASSIGNMENTS, CHECKLIST_ITEMS: read-all | full write any auth
-- ============================================================
CREATE POLICY "task_assignments_read"  ON task_assignments FOR SELECT TO authenticated USING (true);
CREATE POLICY "task_assignments_write" ON task_assignments FOR ALL    TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "checklist_items_read"  ON checklist_items FOR SELECT TO authenticated USING (true);
CREATE POLICY "checklist_items_write" ON checklist_items FOR ALL    TO authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- TASK_COMMENTS: read-all | insert any auth | update/delete author-or-admin
-- ============================================================
CREATE POLICY "task_comments_read"   ON task_comments FOR SELECT TO authenticated USING (true);
CREATE POLICY "task_comments_insert" ON task_comments FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "task_comments_update" ON task_comments FOR UPDATE TO authenticated
  USING (auth.uid() = user_id OR is_admin())
  WITH CHECK (auth.uid() = user_id OR is_admin());
CREATE POLICY "task_comments_delete" ON task_comments FOR DELETE TO authenticated
  USING (auth.uid() = user_id OR is_admin());

-- ============================================================
-- MENTIONS, PENDING_MENTIONS: read-all | system insert only
-- Server actions write to these; they run with the user's JWT but the writes
-- should be allowed since the action is on the user's behalf.
-- ============================================================
CREATE POLICY "mentions_read"   ON mentions FOR SELECT TO authenticated USING (true);
CREATE POLICY "mentions_insert" ON mentions FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "pending_mentions_read"   ON pending_mentions FOR SELECT TO authenticated USING (true);
CREATE POLICY "pending_mentions_insert" ON pending_mentions FOR INSERT TO authenticated WITH CHECK (true);

-- ============================================================
-- TASK_DEPENDENCIES: read-all | insert/delete any auth
-- ============================================================
CREATE POLICY "task_dependencies_read"   ON task_dependencies FOR SELECT TO authenticated USING (true);
CREATE POLICY "task_dependencies_insert" ON task_dependencies FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "task_dependencies_delete" ON task_dependencies FOR DELETE TO authenticated USING (true);

-- ============================================================
-- RECURRING_TEMPLATES: read-all | insert any auth | update/delete creator-or-admin
-- ============================================================
CREATE POLICY "recurring_templates_read"   ON recurring_templates FOR SELECT TO authenticated USING (true);
CREATE POLICY "recurring_templates_insert" ON recurring_templates FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by);
CREATE POLICY "recurring_templates_update" ON recurring_templates FOR UPDATE TO authenticated
  USING (auth.uid() = created_by OR is_admin())
  WITH CHECK (auth.uid() = created_by OR is_admin());
CREATE POLICY "recurring_templates_delete" ON recurring_templates FOR DELETE TO authenticated
  USING (auth.uid() = created_by OR is_admin());

-- ============================================================
-- BUDGET_PERIODS: read-all | write admin
-- ============================================================
CREATE POLICY "budget_periods_read"        ON budget_periods FOR SELECT TO authenticated USING (true);
CREATE POLICY "budget_periods_admin_write" ON budget_periods FOR ALL    TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- ============================================================
-- ACTIVITY_LOG, WEEKLY_SNAPSHOTS: read-all | system insert only
-- ============================================================
CREATE POLICY "activity_log_read"   ON activity_log FOR SELECT TO authenticated USING (true);
CREATE POLICY "activity_log_insert" ON activity_log FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "weekly_snapshots_read"   ON weekly_snapshots FOR SELECT TO authenticated USING (true);
CREATE POLICY "weekly_snapshots_insert" ON weekly_snapshots FOR INSERT TO authenticated WITH CHECK (true);

-- ============================================================
-- NOTIFICATIONS: read-self-or-admin | system insert | update-self (mark read)
-- ============================================================
CREATE POLICY "notifications_read"   ON notifications FOR SELECT TO authenticated USING (auth.uid() = user_id OR is_admin());
CREATE POLICY "notifications_insert" ON notifications FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "notifications_update" ON notifications FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ============================================================
-- SLACK_SETTINGS, PENDING_SLACK_NOTIFICATIONS: admin-only across the board
-- ============================================================
CREATE POLICY "slack_settings_admin" ON slack_settings FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY "pending_slack_notifications_read"  ON pending_slack_notifications FOR SELECT TO authenticated USING (is_admin());
CREATE POLICY "pending_slack_notifications_write" ON pending_slack_notifications FOR ALL    TO authenticated USING (true) WITH CHECK (true);
-- write is open so server actions can queue without being admin; reads are admin-only.

-- ============================================================
-- HUBSPOT: connection admin-only; synced_contacts any-auth read
-- ============================================================
CREATE POLICY "hubspot_connection_admin" ON hubspot_connection FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY "hubspot_synced_contacts_read"  ON hubspot_synced_contacts FOR SELECT TO authenticated USING (true);
CREATE POLICY "hubspot_synced_contacts_write" ON hubspot_synced_contacts FOR ALL    TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- ============================================================
-- PENDING_INVITES, PENDING_ASSIGNMENTS: admin-only for invites; any-auth for assignments
-- ============================================================
CREATE POLICY "pending_invites_admin" ON pending_invites FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

CREATE POLICY "pending_assignments_read"  ON pending_assignments FOR SELECT TO authenticated USING (true);
CREATE POLICY "pending_assignments_write" ON pending_assignments FOR ALL    TO authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- DONE.
-- ============================================================

-- ############################################################
-- 009_saved_views.sql
-- ############################################################
-- ============================================================
-- MIGRATION 009: Saved Views (BACKLOG #19)
--
-- Why this exists:
--   Users want to save a named filter/sort configuration on a page
--   (e.g. the Global Tracker) and reload it later — "My P0s due this week"
--   style bookmarks (spec §, backlog item 19).
--
--   A saved view is purely per-user: each user only ever sees and manages
--   their OWN views. The shape of the config is opaque JSON owned by the
--   page that created it (keyed by `page`), so we don't couple the schema
--   to any one page's filter set.
--
-- Idempotent. Safe to re-run.
-- ============================================================

-- ---------- 1. saved_views table ----------
CREATE TABLE IF NOT EXISTS saved_views (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- Which page/surface the view belongs to (e.g. 'tracker', 'my-tasks').
  page TEXT NOT NULL,
  name TEXT NOT NULL,
  -- Opaque filter/sort configuration owned by the page that created it.
  config JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- A user can't have two views with the same name on the same page.
  UNIQUE (user_id, page, name)
);

CREATE INDEX IF NOT EXISTS saved_views_user_page_idx
  ON saved_views(user_id, page);

-- ---------- 2. RLS: users see / manage ONLY their own views ----------
ALTER TABLE saved_views ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "saved_views_select" ON saved_views;
DROP POLICY IF EXISTS "saved_views_insert" ON saved_views;
DROP POLICY IF EXISTS "saved_views_update" ON saved_views;
DROP POLICY IF EXISTS "saved_views_delete" ON saved_views;

CREATE POLICY "saved_views_select" ON saved_views FOR SELECT TO authenticated
  USING (auth.uid() = user_id);
CREATE POLICY "saved_views_insert" ON saved_views FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);
CREATE POLICY "saved_views_update" ON saved_views FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
CREATE POLICY "saved_views_delete" ON saved_views FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

-- ============================================================
-- DONE.
-- ============================================================

-- ############################################################
-- 010_gtm_blueprint_extensions.sql
-- ############################################################
-- ============================================================
-- Migration 010: GTM blueprint extensions
-- Adds the channel-level concepts the GSI_GTM_2 blueprint has and
-- the schema lacked: tier, goal, target, budget note, extra flags,
-- channel owners (by email, pre-sign-in), resources, learnings.
-- Idempotent: safe to re-run (IF NOT EXISTS / DROP POLICY IF EXISTS),
-- matching the style of migrations 005/007/008/009.
-- ============================================================

-- ---------- 0. Priority scale P0-P4 ----------
-- The GTM board uses a five-step priority scale; 001 defined only P0-P3.
-- (PG12+: allowed in a transaction as long as the new value isn't used in the
-- same transaction — the seed script writes P4 later, over the API.)
ALTER TYPE task_priority ADD VALUE IF NOT EXISTS 'P4';

-- ---------- 1. Channel metadata columns ----------

ALTER TABLE channels ADD COLUMN IF NOT EXISTS tier TEXT
  CHECK (tier IN ('gold', 'silver', 'bronze', 'hygiene'));
ALTER TABLE channels ADD COLUMN IF NOT EXISTS goal TEXT;
ALTER TABLE channels ADD COLUMN IF NOT EXISTS target TEXT;
ALTER TABLE channels ADD COLUMN IF NOT EXISTS budget_note TEXT;
-- extra holds blueprint flags with no first-class column:
-- { num, color, opp_target, is_new, onote, platforms }
ALTER TABLE channels ADD COLUMN IF NOT EXISTS extra JSONB NOT NULL DEFAULT '{}'::jsonb;

-- ---------- 2. Channel owners (by email, resolved on first sign-in) ----------

CREATE TABLE IF NOT EXISTS channel_owners (
  channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (channel_id, email)
);

CREATE INDEX IF NOT EXISTS channel_owners_email_idx ON channel_owners(email);
CREATE INDEX IF NOT EXISTS channel_owners_user_idx ON channel_owners(user_id);

-- ---------- 3. Channel resources (the board's {name, url} links) ----------

CREATE TABLE IF NOT EXISTS channel_resources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  added_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS channel_resources_channel_idx ON channel_resources(channel_id);

-- ---------- 3b. Channel targets (multiple per channel/sub-channel) ----------

CREATE TABLE IF NOT EXISTS channel_targets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  added_by UUID REFERENCES users(id) ON DELETE SET NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS channel_targets_channel_idx ON channel_targets(channel_id);

-- ---------- 4. Channel learnings (append-only retro notes) ----------

CREATE TABLE IF NOT EXISTS channel_learnings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  added_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS channel_learnings_channel_idx ON channel_learnings(channel_id);

-- ---------- 5. RLS ----------
-- Posture mirrors 008: taxonomy structure (owners) is admin-write,
-- collaborative content (resources, learnings) is member-writable.

ALTER TABLE channel_owners    ENABLE ROW LEVEL SECURITY;
ALTER TABLE channel_resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE channel_learnings ENABLE ROW LEVEL SECURITY;
ALTER TABLE channel_targets   ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "channel_targets_read"   ON channel_targets;
DROP POLICY IF EXISTS "channel_targets_insert" ON channel_targets;
DROP POLICY IF EXISTS "channel_targets_delete" ON channel_targets;
CREATE POLICY "channel_targets_read"   ON channel_targets FOR SELECT TO authenticated USING (true);
CREATE POLICY "channel_targets_insert" ON channel_targets FOR INSERT TO authenticated
  WITH CHECK (added_by = auth.uid() OR is_admin());
CREATE POLICY "channel_targets_delete" ON channel_targets FOR DELETE TO authenticated
  USING (added_by = auth.uid() OR is_admin());

DROP POLICY IF EXISTS "channel_owners_read"        ON channel_owners;
DROP POLICY IF EXISTS "channel_owners_admin_write" ON channel_owners;
CREATE POLICY "channel_owners_read"        ON channel_owners FOR SELECT TO authenticated USING (true);
CREATE POLICY "channel_owners_admin_write" ON channel_owners FOR ALL    TO authenticated USING (is_admin()) WITH CHECK (is_admin());

DROP POLICY IF EXISTS "channel_resources_read"   ON channel_resources;
DROP POLICY IF EXISTS "channel_resources_insert" ON channel_resources;
DROP POLICY IF EXISTS "channel_resources_update" ON channel_resources;
DROP POLICY IF EXISTS "channel_resources_delete" ON channel_resources;
CREATE POLICY "channel_resources_read"   ON channel_resources FOR SELECT TO authenticated USING (true);
-- Pin authorship (mirrors 008's task_comments pattern): a member may only
-- insert rows attributed to themselves, so added_by can't be forged or NULLed.
CREATE POLICY "channel_resources_insert" ON channel_resources FOR INSERT TO authenticated
  WITH CHECK (added_by = auth.uid() OR is_admin());
CREATE POLICY "channel_resources_update" ON channel_resources FOR UPDATE TO authenticated
  USING (added_by = auth.uid() OR is_admin()) WITH CHECK (added_by = auth.uid() OR is_admin());
CREATE POLICY "channel_resources_delete" ON channel_resources FOR DELETE TO authenticated
  USING (added_by = auth.uid() OR is_admin());

DROP POLICY IF EXISTS "channel_learnings_read"   ON channel_learnings;
DROP POLICY IF EXISTS "channel_learnings_insert" ON channel_learnings;
DROP POLICY IF EXISTS "channel_learnings_delete" ON channel_learnings;
CREATE POLICY "channel_learnings_read"   ON channel_learnings FOR SELECT TO authenticated USING (true);
CREATE POLICY "channel_learnings_insert" ON channel_learnings FOR INSERT TO authenticated
  WITH CHECK (added_by = auth.uid() OR is_admin());
CREATE POLICY "channel_learnings_delete" ON channel_learnings FOR DELETE TO authenticated
  USING (added_by = auth.uid() OR is_admin());

-- ---------- 6. Extend handle_new_user: resolve channel ownership ----------
-- Full body carried forward from migration 007 (users mirror, pending
-- mentions, pending invites, pending assignments) + NEW channel_owners step.

CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.users (id, email, display_name, avatar_url, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
    NEW.raw_user_meta_data->>'avatar_url',
    CASE WHEN NEW.email = 'kailash.gm@lyzr.ai' THEN 'admin'::user_role ELSE 'member'::user_role END
  );

  UPDATE pending_mentions
     SET resolved_user_id = NEW.id, resolved_at = now()
   WHERE email = NEW.email AND resolved_user_id IS NULL;

  INSERT INTO mentions (task_id, surface, surface_ref_id, mentioned_user_id, mentioned_email, mentioned_by)
  SELECT pm.task_id, pm.surface, pm.surface_ref_id, NEW.id, NEW.email, NEW.id
    FROM pending_mentions pm
   WHERE pm.email = NEW.email AND pm.resolved_user_id = NEW.id;

  UPDATE pending_invites
     SET resolved_user_id = NEW.id, resolved_at = now()
   WHERE email = NEW.email AND resolved_user_id IS NULL;

  -- Materialize pending assignments. A pending 'primary' demotes to 'other'
  -- when the task already has a primary (task_assignments_primary_unique is a
  -- partial unique index that ON CONFLICT (task_id,user_id) cannot absorb) —
  -- seeded data must never be able to make sign-up itself fail.
  INSERT INTO task_assignments (task_id, user_id, role, assigned_by)
  SELECT pa.task_id, NEW.id,
         CASE
           WHEN pa.role = 'primary' AND EXISTS (
             SELECT 1 FROM task_assignments ta
              WHERE ta.task_id = pa.task_id AND ta.role = 'primary'
           ) THEN 'secondary'::assignment_role
           ELSE pa.role
         END,
         pa.assigned_by
    FROM pending_assignments pa
   WHERE pa.email = NEW.email AND pa.resolved_user_id IS NULL
  ON CONFLICT (task_id, user_id) DO NOTHING;

  UPDATE pending_assignments
     SET resolved_user_id = NEW.id, resolved_at = now()
   WHERE email = NEW.email AND resolved_user_id IS NULL;

  -- NEW (010): link channel ownership rows seeded by email
  UPDATE channel_owners
     SET user_id = NEW.id
   WHERE email = NEW.email AND user_id IS NULL;

  RETURN NEW;
END;
$$;

-- ############################################################
-- 011_lead_tracking.sql
-- ############################################################
-- ============================================================
-- Migration 011: Lead dashboards (HubSpot pull + CSV email interactions)
-- HubSpot is READ-ONLY (pulled, never written). Outreach statuses live here.
-- One tracking table serves both dashboards: ref_id is a HubSpot contact id
-- for pulled leads, or 'email:<address>' for CSV-imported leads.
-- Idempotent. Safe to re-run. PASTE INTO SUPABASE SQL EDITOR.
-- ============================================================

-- Extra companies (on top of the built-in pull rule)
CREATE TABLE IF NOT EXISTS lead_companies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  added_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Per-lead outreach state (dropdown stages)
CREATE TABLE IF NOT EXISTS lead_tracking (
  ref_id TEXT PRIMARY KEY,
  email_stage TEXT CHECK (email_stage IN ('e1', 'e2', 'e3')),
  call_status TEXT CHECK (call_status IN ('yes', 'no', 'declined', 'no_response', 'scheduled', 'done', 'no_show')),
  li_stage TEXT CHECK (li_stage IN ('conn', 'm1', 'm2')),
  wa_status TEXT CHECK (wa_status IN ('sent', 'not_demo')),
  updated_by UUID REFERENCES users(id) ON DELETE SET NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- CSV-imported email-interaction leads — retained indefinitely across uploads
CREATE TABLE IF NOT EXISTS email_leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL UNIQUE,
  name TEXT,
  company TEXT,
  demo_click_date DATE,
  -- every other column from the uploaded CSV, shown verbatim on the dashboard
  extra JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_file TEXT,
  uploaded_by UUID REFERENCES users(id) ON DELETE SET NULL,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS email_leads_demo_date_idx ON email_leads(demo_click_date);

-- If lead_tracking pre-dates the 2026-08-05 option change, refresh its CHECKs
UPDATE lead_tracking SET wa_status = NULL WHERE wa_status = 'not_sent';
ALTER TABLE lead_tracking DROP CONSTRAINT IF EXISTS lead_tracking_call_status_check;
ALTER TABLE lead_tracking ADD CONSTRAINT lead_tracking_call_status_check
  CHECK (call_status IN ('yes', 'no', 'declined', 'no_response', 'scheduled', 'done', 'no_show'));
ALTER TABLE lead_tracking DROP CONSTRAINT IF EXISTS lead_tracking_wa_status_check;
ALTER TABLE lead_tracking ADD CONSTRAINT lead_tracking_wa_status_check
  CHECK (wa_status IN ('sent', 'not_demo'));

ALTER TABLE lead_companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE lead_tracking  ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_leads    ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "lead_companies_read"  ON lead_companies;
DROP POLICY IF EXISTS "lead_companies_write" ON lead_companies;
CREATE POLICY "lead_companies_read"  ON lead_companies FOR SELECT TO authenticated USING (true);
CREATE POLICY "lead_companies_write" ON lead_companies FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "lead_tracking_read"  ON lead_tracking;
DROP POLICY IF EXISTS "lead_tracking_write" ON lead_tracking;
CREATE POLICY "lead_tracking_read"  ON lead_tracking FOR SELECT TO authenticated USING (true);
CREATE POLICY "lead_tracking_write" ON lead_tracking FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "email_leads_read"  ON email_leads;
DROP POLICY IF EXISTS "email_leads_write" ON email_leads;
CREATE POLICY "email_leads_read"  ON email_leads FOR SELECT TO authenticated USING (true);
CREATE POLICY "email_leads_write" ON email_leads FOR ALL TO authenticated USING (true) WITH CHECK (true);

GRANT ALL ON lead_companies, lead_tracking, email_leads TO authenticated, service_role;

-- ############################################################
-- 012_recurrence_builder.sql
-- ############################################################
-- ============================================================
-- Migration 012: Google-Calendar-style recurrence
-- Adds "repeat every N day/week/month", specific weekdays for weekly
-- recurrence, and an explicit end condition (never / on date / after N
-- occurrences) to recurring_templates. The old pattern/custom_interval_days/
-- ends_on columns are kept (still NOT NULL) and are written as a best-fit
-- label for backward compatibility, but are no longer used for date math.
-- Idempotent. Safe to re-run. PASTE INTO SUPABASE SQL EDITOR.
-- ============================================================

ALTER TABLE recurring_templates
  ADD COLUMN IF NOT EXISTS interval_count INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS interval_unit TEXT NOT NULL DEFAULT 'week',
  ADD COLUMN IF NOT EXISTS by_weekdays SMALLINT[],
  ADD COLUMN IF NOT EXISTS end_type TEXT NOT NULL DEFAULT 'never',
  ADD COLUMN IF NOT EXISTS occurrences_total INT,
  ADD COLUMN IF NOT EXISTS occurrences_done INT NOT NULL DEFAULT 1;

ALTER TABLE recurring_templates DROP CONSTRAINT IF EXISTS recurring_templates_interval_unit_check;
ALTER TABLE recurring_templates ADD CONSTRAINT recurring_templates_interval_unit_check
  CHECK (interval_unit IN ('day', 'week', 'month'));

ALTER TABLE recurring_templates DROP CONSTRAINT IF EXISTS recurring_templates_end_type_check;
ALTER TABLE recurring_templates ADD CONSTRAINT recurring_templates_end_type_check
  CHECK (end_type IN ('never', 'on_date', 'after_count'));

ALTER TABLE recurring_templates DROP CONSTRAINT IF EXISTS recurring_templates_interval_count_check;
ALTER TABLE recurring_templates ADD CONSTRAINT recurring_templates_interval_count_check
  CHECK (interval_count >= 1);

-- Backfill existing rows from the legacy pattern so already-recurring tasks
-- keep advancing on the same schedule under the new engine.
UPDATE recurring_templates SET
  interval_count = CASE pattern
    WHEN 'daily' THEN 1
    WHEN 'weekly' THEN 1
    WHEN 'biweekly' THEN 2
    WHEN 'monthly' THEN 1
    WHEN 'custom' THEN GREATEST(1, COALESCE(custom_interval_days, 7))
    ELSE 1
  END,
  interval_unit = CASE pattern
    WHEN 'daily' THEN 'day'
    WHEN 'weekly' THEN 'week'
    WHEN 'biweekly' THEN 'week'
    WHEN 'monthly' THEN 'month'
    WHEN 'custom' THEN 'day'
    ELSE 'week'
  END,
  end_type = CASE WHEN ends_on IS NOT NULL THEN 'on_date' ELSE 'never' END
WHERE interval_count = 1 AND interval_unit = 'week' AND end_type = 'never';
-- (the WHERE guards against re-stamping rows already migrated or created
-- fresh under the new engine on a re-run)

-- ############################################################
-- 013_weekly_reports.sql
-- ############################################################
-- ============================================================
-- Migration 013: Weekly Report generator
-- Backs the "Create Weekly Report" button on /weekly: a manual ad-spend
-- ledger (no ads-platform integration exists yet), free-form "done" items
-- that do NOT create real tasks, and the generated report HTML itself,
-- keyed by ISO week_starting (Monday) to match weekly_snapshots.
-- Idempotent. Safe to re-run. PASTE INTO SUPABASE SQL EDITOR.
-- ============================================================

CREATE TABLE IF NOT EXISTS report_ad_spend (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  week_starting DATE NOT NULL,
  platform TEXT NOT NULL,
  campaign TEXT,
  spend NUMERIC(12,2) NOT NULL DEFAULT 0,
  leads INT,
  notes TEXT,
  added_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS report_ad_spend_week_idx ON report_ad_spend(week_starting);

-- Free-form "task / subtask done" bullets for the report only — explicitly
-- NOT rows in the `tasks` table, so they never appear on any tracker board.
CREATE TABLE IF NOT EXISTS report_done_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  week_starting DATE NOT NULL,
  task_title TEXT NOT NULL,
  subtask_title TEXT,
  sort_order INT NOT NULL DEFAULT 0,
  added_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS report_done_items_week_idx ON report_done_items(week_starting);

-- The generated report itself. "Create Weekly Report" upserts this row for
-- the selected week; `summary` keeps the structured inputs so the report can
-- be regenerated/edited later without re-deriving everything from scratch.
CREATE TABLE IF NOT EXISTS weekly_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  week_starting DATE NOT NULL UNIQUE,
  week_ending DATE NOT NULL,
  html TEXT NOT NULL,
  summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  generated_by UUID REFERENCES users(id) ON DELETE SET NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE report_ad_spend   ENABLE ROW LEVEL SECURITY;
ALTER TABLE report_done_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_reports    ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "report_ad_spend_read"  ON report_ad_spend;
DROP POLICY IF EXISTS "report_ad_spend_write" ON report_ad_spend;
CREATE POLICY "report_ad_spend_read"  ON report_ad_spend FOR SELECT TO authenticated USING (true);
CREATE POLICY "report_ad_spend_write" ON report_ad_spend FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "report_done_items_read"  ON report_done_items;
DROP POLICY IF EXISTS "report_done_items_write" ON report_done_items;
CREATE POLICY "report_done_items_read"  ON report_done_items FOR SELECT TO authenticated USING (true);
CREATE POLICY "report_done_items_write" ON report_done_items FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "weekly_reports_read"  ON weekly_reports;
DROP POLICY IF EXISTS "weekly_reports_write" ON weekly_reports;
CREATE POLICY "weekly_reports_read"  ON weekly_reports FOR SELECT TO authenticated USING (true);
CREATE POLICY "weekly_reports_write" ON weekly_reports FOR ALL TO authenticated USING (true) WITH CHECK (true);

GRANT ALL ON report_ad_spend, report_done_items, weekly_reports TO authenticated, service_role;

-- ---------- POST: re-mirror existing auth accounts ----------
-- handle_new_user only fires on INSERT into auth.users, so anyone who signed
-- in before this reset must be backfilled into public.users here.
INSERT INTO public.users (id, email, display_name, avatar_url, role)
SELECT id, email,
       COALESCE(raw_user_meta_data->>'full_name', split_part(email, '@', 1)),
       raw_user_meta_data->>'avatar_url',
       CASE WHEN email = 'kailash.gm@lyzr.ai' THEN 'admin'::user_role ELSE 'member'::user_role END
FROM auth.users
ON CONFLICT (id) DO NOTHING;

-- Belt-and-braces: make sure PostgREST roles can reach everything created above.
GRANT ALL ON ALL TABLES    IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES  IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- ---------- SANITY CHECK ----------
SELECT 'tables' AS what, count(*)::text AS value FROM information_schema.tables WHERE table_schema = 'public'
UNION ALL SELECT 'users mirrored', count(*)::text FROM public.users
UNION ALL SELECT 'categories (expect 0 until seed)', count(*)::text FROM categories
UNION ALL SELECT 'admin present', count(*)::text FROM public.users WHERE role = 'admin';
